### ISSUE TITLE
Extra hearts reset upon world/server restart

### ISSUE THREAD

**Issue by jinkhya** [SpaceCat97/SpaceCats-Wikis#35]
Hello, I'm currently playing Uncharted Expeditions modpack which has this mod but every time the world is saved and closed the hearts are gone and you have to eat every time to heal back. I tried using MaxHealthFix mod which normally works with most mods adding hearts but it doesn't seem to work with ASB. Anything you could do about this?
Thanks in advance,
Jin

**Comment by SpaceCat97** [comment]
Unfortunately this is something that is restricted by vanilla minecraft code. The only way I could make a way around this would be to heal the player when the effect applies - which would easily be abused.
The problem is that ASB adds the hearts **after** the world has been loaded, when mob ticking begins.

I'll continue to keep an eye out for fixes, but this is one of those things that you'll have to live with for now. Hopefully mojang do some sort of fix to their own code.
